name: Build NixOS ISO

on:
  push:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: [self-hosted, linux]
    env:
      USER: runner
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build GLF-OS ISO
        run: nix run github:Mic92/nix-fast-build -- --no-nom  --skip-cached --systems 'x86_64-linux' -f .#iso         

      - name: Debug Build Output
        run: |
          echo "Contents of result:"
          ls -l ./result

      - name: Resolve ISO path
        id: resolve_path
        run: |
          ISO_PATH=$(readlink -f ./result)
          echo "ISO file resolved to: $ISO_PATH"
          echo "iso_path=$ISO_PATH" >> $GITHUB_ENV

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-iso
          path: ${{ env.iso_path }}
