name: Build NixOS ISO

on:
  push:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build NixOS ISO
        run: nix --extra-experimental-features "nix-command flakes" build -L .#iso

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-iso
          path: ./result/*.iso
