name: Build GLF-OS Configurations

on:
  push:
    branches: [main, dev]
    paths:
      - '**/*.nix'
      - '**/*.lock'

  pull_request:
    branches: ['**'] 
    paths:
      - '**/*.nix'
      - '**/*.lock'

  workflow_dispatch:

jobs:
  buildGLF-Configurations:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build GLF
        run: nix flake check --no-build
        continue-on-error: false

  report:
    name: Final Status
    runs-on: ubuntu-latest
    needs: [buildGLF-Configurations]
    steps:
      - name: Combine Results
        run: |
          echo "Build status:"
          echo "✅ Testing completed"
        if: always()
