name: Update flake and try build

on:
  push:
    branches:
      - dev
      - workflow-nix
  # schedule:
  #   - cron: '0 0 * * 0'  # Exécution tous les dimanche à minuit
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]
    env:
      USER: runner
    steps:
      - uses: actions/checkout@v3

      # Installer Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      # Mettre à jour le flocon Nix
      - name: Update Nix Flake
        run: nix flake update

      # Ajouter flake.lock à l'index et valider si modifié
      - name: Update Nix Flake and Build if modified
        run: |
          # Vérifie les modifications de flake.lock
          echo "Vérification de l'état de flake.lock"
          git status --short flake.lock
          
          # Ajoute un test de différence plus détaillé
          if git diff --exit-code flake.lock; then
            echo "flake.lock n'a pas été modifié"
          else
            echo "flake.lock a été modifié"
            # Démarre la construction
            nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached --systems 'x86_64-linux' -f .#nixosConfigurations.glf-installer.config.system.build.toplevel
          fi

      # Créer une pull request si la construction réussit
      - name: Create Pull Request
        if: success() && env.flake_lock_updated == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'Update GLF-OS flake'
          title: 'Update GLF-OS flake'
          body: |
            This PR update flake.lock and build.
          base: dev
          branch: update/flake
