name: Update flake and try build

on:
  push:
    branches:
      - dev
      - workflow-nix
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]
    env:
      USER: runner
    steps:
      - uses: actions/checkout@v3

      # Installer Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      # Mettre à jour le flocon Nix
      - name: Update Nix Flake
        run: nix flake update

      # Vérifier si flake.lock a été modifié
      - name: Check if flake.lock is modified
        id: check_flake
        run: |
          # Vérifie si flake.lock a été modifié
          if git diff --exit-code flake.lock; then
            echo "flake.lock n'a pas été modifié"
            echo "flake_lock_modified=false" >> $GITHUB_ENV
          else
            echo "flake.lock a été modifié"
            echo "flake_lock_modified=true" >> $GITHUB_ENV
          fi

  # Nouvelle tâche 'nix build' qui se déclenche si flake.lock a changé
  nix_build:
    runs-on: [self-hosted, linux]
    needs: build
    if: ${{ env.flake_lock_modified == 'true' }}
    steps:
      - name: Build with Nix
        run: |
          echo "Démarrage de la construction Nix"
          nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached --systems 'x86_64-linux' -f .#nixosConfigurations.glf-installer.config.system.build.toplevel

      # Créer une pull request si la construction réussit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'Update GLF-OS flake'
          title: 'Update GLF-OS flake'
          body: |
            This PR updates flake.lock and build.
          base: dev
          branch: update/flake
