name: Update flake and try build

on:
  push:
    branches:
      - dev
      - workflow-nix
  # schedule:
  #   - cron: '0 0 * * 0'  # Exécution tous les dimanche à minuit
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]
    env:
      USER: runner
    steps:
      - uses: actions/checkout@v3

      # Installer Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      # Mettre à jour le flocon Nix
      - name: Update Nix Flake
        run: nix flake update

      # Ajouter flake.lock à l'index et valider si modifié
      - name: Commit updated flake.lock if modified
        id: commit_flake_lock
        run: |
          git add flake.lock
          git status
          if ! git diff --quiet flake.lock; then
            git commit -m "Update flake.lock"
            echo "flake_lock_updated=true" >> $GITHUB_ENV
          else
            echo "flake_lock_updated=false" >> $GITHUB_ENV
          fi

      # Construire la configuration NixOS si flake.lock a été modifié
      - name: Build with Nix
        if: env.flake_lock_updated == 'true'
        run: nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached --systems 'x86_64-linux' -f .#nixosConfigurations.glf-installer.config.system.build.toplevel
        # continue-on-error: false

      # Créer une pull request si la construction réussit
      - name: Create Pull Request
        if: success() && env.flake_lock_updated == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'Update GLF-OS flake'
          title: 'Update GLF-OS flake'
          body: |
            This PR update flake.lock and build.
          base: dev
          branch: update/flake
