name: Nix Build Configurations

on:
  push:
    branches:
      - main
      - dev
      - workflow-nix
  pull_request:
    branches:
      - main
      - dev
      - workflow-nix

jobs:
  build:
    runs-on: [self-hosted, linux]
    env:
      USER: runner
    steps:
      - uses: actions/checkout@v3

      # Installer Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      # Construire la configuration NixOS
      - name: Build with Nix
        run: nix --extra-experimental-features "nix-command flakes" build -L .#nixosConfigurations.glf-installer.config.system.build.toplevel
