name: Nix Build

on:
  push:
    branches:
      - main
      - dev
    pull_request:
      branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build with Nix
	run: nix run github:Mic92/nix-fast-build -- --flake .#nixosConfigurations.glf-installer.config.system.build.toplevel



